const vip_urls = [
  '/api/account/IndexDetail',
  '/api/account/IsVip',
  '/api/account/UserSetting',
  '/api/account/TabRedTip',
  '/api/Account/Suport',
  '/api/cartoon/VipInfo',
  '/api/cartoon/GetAllTagNew',
  '/api/cartoon/indexNew/*',
  '/api/cartoon/LookPhotoVip/*',
  '/api/cartoon/CheckCartoonVip/*',
  '/api/Adv/VuePage/*',
  '/api/PictureSet/OpenPictureSetFree',
  '/api/PictureSet/LookPhoto/*',
  '/api/Download/CheckDownloadTorrent',
  '/api/Movie/Commoent/*',
  '/api/Movie/WatchMovie',
  '/api/video/watch/*'
];
